image: debian:bookworm

.common_only: &common_only
    only:
        - main
        - merge_requests

variables:
    GIT_STRATEGY: clone

stages:
    - lint
    - tuttest

pre-commit:
    <<: *common_only
    stage: lint
    script:
        - apt-get update -y
        - apt-get install -y clang-format git pre-commit
        - pre-commit run --all-files

tuttest:
    <<: *common_only
    stage: tuttest
    before_script:
        - DEBIAN_FRONTEND=noninteractive apt-get update -y && apt-get install -y --no-install-recommends
              python3 python3-pip git colorized-logs sudo fonts-lato
        - rm /usr/lib/python3.11/EXTERNALLY-MANAGED
        - python3 -m pip install git+https://github.com/antmicro/tuttest.git
    script:
        - bash <(echo -e 'set -ex\n' && tuttest --language bash README.md | grep -v '^\$')
